import { useMemo, useState } from 'react'
import { Download, FileDown, Maximize, Minus, Plus, Search, ShieldCheck } from 'lucide-react'
import RecordTable from '../ui/RecordTable.jsx'
import { configureApiBaseUrl, getApiBaseUrl } from '../../services/apiClient.js'
import { USE_MOCK_DATA } from '../../services/serviceFactory.js'

const MODE_META=USE_MOCK_DATA?'DEMO MODE · MOCK DATA':'API MODE · LIVE DATA'
const MODE_CHIP=USE_MOCK_DATA?'MOCK DATA':'API DATA'
const severity=(value)=> <span className={`severity-label ${String(value).toLowerCase()}`}>{value}</span>
const risk=(value)=>value==null?'—':<b className={`risk-number ${value>=95?'critical':value>=80?'high':value>=60?'medium':value>=30?'low':'legitimate'}`}>{value}</b>
const percent=(value)=>value==null?'—':`${value}%`
const severityCount=(rows,level)=>rows.filter(row=>String(row.severity||'').toLowerCase()===level).length
const statusCount=(rows,status)=>rows.filter(row=>String(row.status||'').toLowerCase()===status).length
function EmptyState({title='No records available',message='There is no mock or API data to display for this view.'}){return <div className="intelligence-empty"><Search size={19}/><b>{title}</b><span>{message}</span></div>}
function Heading({title,description,meta=MODE_META}){return <div className="page-title"><div><small>{meta}</small><h1>{title}</h1><p>{description}</p></div><span className="demo-chip">{MODE_CHIP}</span></div>}
function FilterBar({search,setSearch,options=[],filter,setFilter}){const keys={Severity:'severity',Type:'type',Platform:'platform',Status:'status',Asset:'asset',Store:'store',Date:'date'};return <div className="page-filters"><label><Search size={15}/><input placeholder="Search threats..." value={search} onChange={e=>setSearch(e.target.value)}/></label>{options.map(([label,values])=><select aria-label={label} key={label} onChange={e=>setFilter({...filter,[keys[label]||label.toLowerCase()]:e.target.value})}><option value="">{label}</option>{values.map(v=><option key={v}>{v}</option>)}</select>)}</div>}
function Listing({title,description,rows,columns,onSelect,options=[],summaryCards}){const [search,setSearch]=useState(''),[filter,setFilter]=useState({});const filtered=useMemo(()=>rows.filter(row=>Object.values(row).some(v=>String(v).toLowerCase().includes(search.toLowerCase()))&&Object.entries(filter).every(([key,val])=>!val||(key==='date'?Boolean(row.createdAt):String(row[key]||'').toLowerCase()===val.toLowerCase()))),[rows,search,filter]);const chipCounts=USE_MOCK_DATA?[22,3,7,12]:[rows.length,severityCount(rows,'critical'),severityCount(rows,'high'),severityCount(rows,'medium')];return <>{summaryCards&&<div className="mini-kpis">{summaryCards.map(([x,n])=><div key={x}>{severity(x)}<b>{n}</b></div>)}</div>}<Heading title={title} description={description}/><div className="list-summary"><span>{filtered.length} records <i>·</i> Authorized scope only</span><div>{['All','Critical','High','Medium'].map((x,i)=><span key={x} className={`summary-chip ${i===0?'selected':''}`}>{x}<b>{chipCounts[i]}</b></span>)}</div></div><FilterBar search={search} setSearch={setSearch} options={options} filter={filter} setFilter={setFilter}/><RecordTable columns={columns} rows={filtered} onSelect={onSelect}/></>}

export function ThreatInbox({rows,onSelect}){return <Listing title="Threat Inbox" description="Unified prioritized detections across monitored brand identities and authorized assets." rows={rows} onSelect={onSelect} options={[["Severity",['Critical','High','Medium','Low']],['Type',['Fake Account','Phishing','Vulnerability','Fake Application']],['Platform',['Social','Domain','Demo App Store','Authorized asset']],['Status',['New','Open','Investigating','Resolved']],['Date',['Today','Last 7 days']]]} columns={[{key:'severity',label:'Severity',render:r=>severity(r.severity)},{key:'name',label:'Threat',render:r=><b>{r.name}</b>},{key:'type',label:'Type'},{key:'asset',label:'Asset'},{key:'risk',label:'Risk',render:r=>risk(r.risk)},{key:'confidence',label:'Confidence',render:r=>percent(r.confidence)},{key:'status',label:'Status'},{key:'time',label:'Detected'}]}/>}
export function FakeAccounts({rows,onSelect}){return <Listing summaryCards={USE_MOCK_DATA?[['Detected',14],['Critical',5],['High',6],['Review',3]]:[['Detected',rows.length],['Critical',severityCount(rows,'critical')],['High',severityCount(rows,'high')],['Review',statusCount(rows,'reviewing')]]} title="Fake Account Intelligence" description={USE_MOCK_DATA?'Compare suspicious profiles with authorized brand identities. Similarity values are mock assessments.':'Compare suspicious profiles with authorized brand identities.'} rows={rows} onSelect={onSelect} options={[["Platform",['X','Instagram','LinkedIn','Facebook']],["Severity",['Critical','High','Medium','Low']],["Status",['Critical','Review','Legitimate']]]} columns={[{key:'username',label:'Username',render:r=><b>{r.username}</b>},{key:'platform',label:'Platform'},{key:'followers',label:'Followers'},{key:'age',label:'Age'},{key:'similarity',label:'Similarity',render:r=>percent(r.similarity)},{key:'confidence',label:'AI confidence',render:r=>percent(r.confidence)},{key:'risk',label:'Risk',render:r=>risk(r.risk)},{key:'status',label:'Status',render:r=>severity(r.status)}]}/>}
export function Vulnerabilities({rows,onSelect}){return <><div className="mini-kpis">{(USE_MOCK_DATA?[['Critical',1],['High',2],['Medium',3],['Low',1]]:[['Critical',severityCount(rows,'critical')],['High',severityCount(rows,'high')],['Medium',severityCount(rows,'medium')],['Low',severityCount(rows,'low')]]).map(([x,n])=><div key={x}>{severity(x)}<b>{n}</b></div>)}</div><Listing title="Vulnerability Center" description="Authorized inventory findings only · scanner and API integrations are not connected." rows={rows} onSelect={onSelect} options={[["Severity",['Critical','High','Medium','Low']],['Status',['Open','In progress','Resolved']]]} columns={[{key:'id',label:'ID'},{key:'asset',label:'Asset'},{key:'finding',label:'Finding'},{key:'severity',label:'Severity',render:r=>severity(r.severity)},{key:'risk',label:'Risk',render:r=>risk(r.risk)},{key:'cve',label:'CVE'},{key:'status',label:'Status'},{key:'detected',label:'Detected'}]}/></>}
export function Domains({rows,onSelect}){const summary=USE_MOCK_DATA?[['Official domains',1],['Suspicious domains',6],['Typosquats',4],['Phishing domains',9]]:[['Domain candidates',rows.filter(r=>r.classification==='DOMAIN').length],['Website candidates',rows.filter(r=>r.classification==='WEBSITE').length]];return <><div className="domain-summary">{summary.map(([x,n])=><div key={x}><small>{x}</small><b>{n}</b></div>)}</div><Listing title="Domain Intelligence" description={USE_MOCK_DATA?'Lookalike and phishing indicators from mock data. No domain scanning is performed.':'Lookalike and phishing indicators from registered candidate records. No domain scanning is performed.'} rows={rows} onSelect={onSelect} columns={[{key:'domain',label:'Domain',render:r=><b>{r.domain}</b>},{key:'classification',label:'Classification'},{key:'similarity',label:'Similarity',render:r=>percent(r.similarity)},{key:'age',label:'Domain age'},{key:'ssl',label:'SSL'},{key:'risk',label:'Risk',render:r=>risk(r.risk)},{key:'status',label:'Status'}]}/> </>}
export function Applications({rows,onSelect}){return <Listing title="Application Intelligence" description={USE_MOCK_DATA?'Potential app impersonation from mock store records.':'Potential app impersonation from registered candidate records.'} rows={rows} onSelect={onSelect} options={[["Store",['Demo App Store','Demo Android Store']],['Status',['Critical','Review']]]} columns={[{key:'name',label:'App name',render:r=><b>{r.name}</b>},{key:'store',label:'Store'},{key:'developer',label:'Developer'},{key:'package',label:'Package'},{key:'logoSimilarity',label:'Logo similarity',render:r=>percent(r.logoSimilarity)},{key:'descriptionSimilarity',label:'Description',render:r=>percent(r.descriptionSimilarity)},{key:'risk',label:'Risk',render:r=>risk(r.risk)},{key:'status',label:'Status'}]}/>}
export function Campaigns({rows,onSelect}){return <><Heading title="Campaign Intelligence" description="Correlated threat records grouped for analyst review."/>{rows.length?<div className="campaign-grid">{rows.map(c=><button key={c.id} className="campaign-feature" onClick={()=>onSelect(c)}><span className="campaign-kicker">{c.id} <i>·</i> {c.status}</span><h2>{c.name}</h2><div className="campaign-facts"><span>Risk <b>{c.risk}</b></span><span>Threats <b>{c.threats}</b></span></div><div className="campaign-related">{c.related.map(x=><span key={x}>{x}</span>)}</div><div className="campaign-timeline">{c.timeline.map((s,i)=><span key={s} className={i<2?'done':''}><i/>{s}</span>)}</div></button>)}</div>:<EmptyState title="No campaigns"/>}</>}
export function EvidenceGraph({data,onSelect}){const [scale,setScale]=useState(1);const nodes=data.nodes||[],byId=Object.fromEntries(nodes.map(n=>[n.id,n]));return <><Heading title="Evidence Graph" description={USE_MOCK_DATA?'Interactive relationships among mock indicators. Select a node to inspect evidence.':'Registered candidate relationships. Open a candidate to run evidence analysis and inspect supporting signals.'}/><div className="graph-tools"><span>Authorized relationship map <small>· {USE_MOCK_DATA?'DEMO GRAPH':'LIVE DATA'}</small></span><button aria-label="Zoom out" onClick={()=>setScale(Math.max(.7,scale-.1))}><Minus/></button><button aria-label="Zoom in" onClick={()=>setScale(Math.min(1.5,scale+.1))}><Plus/></button><button onClick={()=>setScale(1)}>Reset</button><button onClick={()=>setScale(1)}>Fit graph <Maximize/></button></div>{data.note&&<p className="authorized-hint">{data.note}</p>}{nodes.length?<div className="new-graph"><svg viewBox="0 0 1000 500" style={{transform:`scale(${scale})`}} aria-label="Evidence relationship graph">{data.edges.map(([a,b])=>byId[a]&&byId[b]&&<line key={`${a}-${b}`} x1={byId[a].x*10} y1={byId[a].y*5} x2={byId[b].x*10} y2={byId[b].y*5} className="graph-link"/>)}{nodes.map(n=><g key={n.id} transform={`translate(${n.x*10},${n.y*5})`} onClick={()=>onSelect(n)} onKeyDown={event=>event.key==='Enter'&&onSelect(n)} role="button" tabIndex="0" aria-label={`${n.type}: ${n.label}`} className={`evidence-node ${n.type.toLowerCase()}`}><circle r="24"/><text textAnchor="middle" y="4">{n.type.slice(0,2).toUpperCase()}</text><text textAnchor="middle" y="42" className="node-label">{n.label}</text></g>)}</svg></div>:<EmptyState title="No evidence graph available"/>}</>}
export function AIAnalysis({rows}){return <><Heading title="AI Threat Analysis" description={USE_MOCK_DATA?'Explainable mock classifications. AI DEMO ENGINE · no production model connected.':'Explainable classifications from the Aegis analysis engine. Run analyses from a candidate drawer.'} meta={USE_MOCK_DATA?'AI DEMO ENGINE · MOCK DATA':'AEGIS ANALYSIS · API MODE'}/><div className="ai-ready"><span>●</span> {USE_MOCK_DATA?'AI Engine Ready':'Analyses run per candidate'} <small>{USE_MOCK_DATA?'DEMO':'API'}</small></div>{rows.length?rows.map(a=><article key={a.id} className="ai-card"><header><div><small>{a.threatId}</small><h2>{a.threat}</h2></div><div className="ai-scores"><span>Confidence <b>{a.confidence}%</b></span><span>Risk <b>{a.risk} / 100</b></span></div></header><div className="ai-classification"><span>CLASSIFICATION</span><b>{a.classification}</b></div><p>{a.reasoning}</p><h3>Evidence signals</h3><div className="ai-evidence">{a.evidence.map(e=><span key={e}>✓ {e}</span>)}</div><div className="ai-recommendation"><b>Recommendation</b><p>{a.recommendation}</p></div></article>):<EmptyState title="No AI analysis available"/>}</>}

export function SimplePage({page,data,onNavigate,campaigns,brand}) {
 const [enabled,setEnabled]=useState({Social:true,Domains:true,Applications:true,Vulnerabilities:true})
 const [notification,setNotification]=useState('')
 const [apiUrl,setApiUrl]=useState(getApiBaseUrl()||'/api')
 const exportFile=kind=>{
  const keys=Object.keys(data[0]||{})
  const payload=kind==='CSV'?[keys.join(','),...data.map(row=>keys.map(key=>`"${String(row[key]??'').replaceAll('"','""')}"`).join(','))].join('\\n'):JSON.stringify(data,null,2)
  const blob=new Blob([payload],{type:kind==='CSV'?'text/csv':'application/json'})
  const url=URL.createObjectURL(blob),anchor=document.createElement('a')
  anchor.href=url;anchor.download=`aegis-${page.toLowerCase().replaceAll(' ','-')}.${kind==='CSV'?'csv':'json'}`;anchor.click();URL.revokeObjectURL(url)
  setNotification(`${kind} export ready`);setTimeout(()=>setNotification(''),3000)
 }
 if(page==='Reports'){const mockReports=[['Threat Summary',22],['Risk Distribution','3 / 7 / 12'],['Threat Trends','+18%'],['Fake Accounts',14],['Phishing',9],['Vulnerabilities',7],['Campaigns',2]];const apiReports=[['Threat Summary',data.length,'Candidate assets registered'],['Risk Distribution',`${statusCount(data,'pending')} / ${statusCount(data,'reviewing')} / ${statusCount(data,'confirmed')}`,'Pending / Reviewing / Confirmed'],['Threat Trends',data.filter(r=>Date.now()-new Date(r.createdAt).getTime()<7*864e5).length,'Created in last 7 days'],['Fake Accounts',data.filter(r=>r.type==='SOCIAL').length,'SOCIAL candidates'],['Phishing',data.filter(r=>r.type==='DOMAIN'||r.type==='WEBSITE').length,'Domain and website candidates'],['Vulnerabilities',0,'No backend inventory records'],['Campaigns',(campaigns||[]).length,'Correlated campaigns']];return <><Heading title="Reports" description={USE_MOCK_DATA?'Threat posture and operational summaries from the current mock dataset.':'Threat posture and operational summaries from the current API dataset.'}/><div className="report-grid">{(USE_MOCK_DATA?mockReports:apiReports).map(([title,value,note])=><article key={title}><small>{USE_MOCK_DATA?'DEMO REPORT':'API REPORT'}</small><h3>{title}</h3><b>{value}</b><span>{USE_MOCK_DATA?'Current reporting period':note}</span></article>)}</div><div className="report-actions"><button onClick={()=>exportFile('JSON')}><FileDown/> Generate Report</button><button onClick={()=>exportFile('JSON')}><Download/> Export JSON</button><button onClick={()=>exportFile('CSV')}><Download/> Export CSV</button>{notification&&<span role="status">{notification}</span>}</div></>}
 if(page==='Brand Assets'){const bd=brand?.breakdown;const summary=USE_MOCK_DATA?[['Total assets',108],['Domains',22],['Social accounts',46],['Applications',8],['Websites',12],['Infrastructure',20]]:[['Total assets',brand?.assets??0],['Domains',bd?.DOMAIN??0],['Social accounts',bd?.SOCIAL??0],['Applications',bd?.APP??0],['Websites',bd?.WEBSITE??0]];const categories=USE_MOCK_DATA?['Domains','Social Accounts','Applications','Websites','Brand Assets','Infrastructure'].map((title,i)=>({title,count:[22,46,8,12,6,14][i],state:i===1?'Warning':'Healthy'})):[['Social Accounts',bd?.SOCIAL??0],['Applications',bd?.APP??0],['Websites',bd?.WEBSITE??0],['Domains',bd?.DOMAIN??0]].map(([title,count])=>({title,count,state:'Registered'}));return <><Heading title="Brand Assets" description="Authorized assets included in the PaySecure monitoring inventory."/><div className="domain-summary">{summary.map(([title,count])=><div key={title}><small>{title}</small><b>{count}</b></div>)}</div><div className="asset-categories">{categories.map(({title,count,state})=><article key={title}><ShieldCheck/><h3>{title}</h3><b>{count} assets</b><span className={`asset-state ${state==='Warning'?'warning':'healthy'}`}>● {state}</span></article>)}</div><p className="authorized-hint">Only assets you own or are authorized to monitor should be added to this inventory.</p></>}
 if(page==='Settings') return <><Heading title="Settings" description="Configure authorized monitoring scope and platform preferences."/><div className="settings-grid"><article><small>MONITORED BRAND</small><h2>PaySecure</h2><p>{USE_MOCK_DATA?'Brand identity used for illustrative mock monitoring records.':'Brand identity used for authorized monitoring records.'}</p></article><article><small>API CONFIGURATION</small><label>API Base URL<input value={apiUrl} onChange={e=>setApiUrl(e.target.value)}/></label><button className="inspect-button" onClick={()=>{configureApiBaseUrl(apiUrl);setNotification('API base URL updated for this session');setTimeout(()=>setNotification(''),3000)}}>Save API URL</button><p>For persistent setup, use VITE_API_BASE_URL at deployment.</p><span className="demo-chip">{import.meta.env.VITE_USE_MOCK_DATA==='false'?'API MODE':'DEMO MODE · MOCK DATA'}</span>{notification&&<span role="status">{notification}</span>}</article><article><small>MONITORING</small>{Object.entries(enabled).map(([name,value])=><label className="setting-toggle" key={name}>{name}<input type="checkbox" checked={value} onChange={()=>setEnabled(old=>({...old,[name]:!old[name]}))}/></label>)}</article><article><small>AI</small><h3>{USE_MOCK_DATA?'AI Demo Engine':'Aegis analysis engine'}</h3><p>{USE_MOCK_DATA?'Mock analysis enabled. Replace through the AI service interface.':'Analyses run against the authorized API from each candidate drawer.'}</p></article><article><small>NOTIFICATIONS</small><label className="setting-toggle">Critical alerts<input type="checkbox" defaultChecked/></label></article></div></>
 return <><Heading title={page} description={`AEGIS project and service status · ${USE_MOCK_DATA?'DEMO MODE':'API MODE'}`}/><div className="settings-grid"><article><small>DELIVERY STATUS</small><h2>Frontend ready</h2><p>{USE_MOCK_DATA?'UI operates with mock records and can switch to API mode through environment configuration.':'UI is connected to the authorized Aegis API for records and analysis.'}</p></article><article><small>BACKEND INTEGRATION</small><h3>{USE_MOCK_DATA?'Awaiting authorized API services':'API services connected'}</h3><p>API client and endpoint adapters are prepared.</p><button onClick={()=>onNavigate('Settings')} className="text-link">Configure settings →</button></article></div></>
}
