import { useMemo, useState } from 'react'
import { ChevronDown, ChevronRight, ShieldAlert } from 'lucide-react'
import { Card, Gauge } from '../ui/Primitives.jsx'

export function ExposureCard({data}) { return <Card title="Brand Exposure" className="exposure-card"><div className="exposure-body"><Gauge value={data.score} size={150} stroke={10}><div className="exposure-number"><strong>{data.score}</strong><span>/100</span></div></Gauge><div className="exposure-copy"><b>{data.status}</b><strong>↑ {data.change}</strong><span>from last week</span></div></div></Card> }

export function BreakdownCard({data}) { return <Card title="Threat Breakdown" className="breakdown-card"><div className="breakdown-grid">{data.map(item=><div className="breakdown-item" key={item.label}><Gauge value={item.value} max={100} color={item.color} size={67} stroke={6}><strong>{item.value}</strong></Gauge><b className={`tone-${item.tone}`}>{item.label}</b><span className={`delta tone-${item.tone}`}>{item.change.startsWith('-')?'↓':'↑'} {item.change}</span></div>)}</div></Card> }

export function SingleMetric({title,value,description,color}) { return <Card title={title} className="single-metric"><div className="single-metric-body"><Gauge value={value} max={title.includes('Campaign')?4:150} color={color} size={116} stroke={7}><strong>{value}</strong></Gauge><p>{description}</p><button className="round-arrow" aria-label={`Open ${title}`}><ChevronRight size={18}/></button></div></Card> }

export function ActivityChart({data}) {
  const [hover,setHover]=useState(null)
  const points=useMemo(()=>data.map((point,i)=>({x:36+i*(708/(data.length-1)),y:143-point.value*3.4,...point})),[data])
  const path=points.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' '), area=`${path} L ${points.at(-1).x} 150 L ${points[0].x} 150 Z`
  const dayTicks=[{label:'Oct 2',x:36},{label:'Oct 3',x:154},{label:'Oct 4',x:272},{label:'Oct 5',x:390},{label:'Oct 6',x:508},{label:'Oct 7',x:626},{label:'Oct 8',x:744}]
  return <Card title="Threat Activity" className="activity-card" action={<button className="select-button">Last 7 Days <ChevronDown size={13}/></button>}><div className="chart-wrap"><div className="chart-y-labels"><span>40</span><span>30</span><span>20</span><span>10</span><span>0</span></div><svg className="activity-chart" viewBox="0 0 780 180" role="img" aria-label="Threat activity over the last seven days">
    <defs><linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff394f" stopOpacity=".25"/><stop offset="1" stopColor="#ff394f" stopOpacity="0"/></linearGradient><filter id="lineGlow"><feGaussianBlur stdDeviation="3" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
    {[7,41,75,109,143].map(y=><line key={y} x1="36" x2="744" y1={y} y2={y} className="chart-grid"/>)}{dayTicks.map(t=><line key={t.label} x1={t.x} x2={t.x} y1="7" y2="150" className="chart-grid vertical"/>)}
    <path d={area} fill="url(#areaFill)"/><path d={path} className="chart-line" filter="url(#lineGlow)"/>{points.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={hover===i?5:2.7} className="chart-point" onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(i)} tabIndex="0" aria-label={`${p.value} threats, ${p.day}, 2026`}/>)}
    {hover!==null&&<g className="chart-tooltip"><rect x={Math.max(42,Math.min(points[hover].x-39,666))} y={Math.max(4,points[hover].y-57)} width="82" height="43" rx="6"/><text x={Math.max(83,Math.min(points[hover].x+2,707))} y={Math.max(21,points[hover].y-37)} textAnchor="middle">{points[hover].value} threats</text><text x={Math.max(83,Math.min(points[hover].x+2,707))} y={Math.max(37,points[hover].y-20)} textAnchor="middle">{points[hover].day}, 2026</text></g>}
  </svg><div className="chart-x-labels">{dayTicks.map(t=><span key={t.label}>{t.label}</span>)}</div></div></Card>
}

export function RecentThreats({data}) { return <Card title="Recent Threats" className="recent-card" action={<button className="text-link">View all <span>→</span></button>}><div className="threat-list">{data.map(t=><button className="threat-row" key={t.name}><span className={`threat-icon ${t.color}`}>{t.icon}</span><span className="threat-info"><b>{t.name}</b><small>{t.source} <i>·</i> {t.detail}</small></span><strong className={`risk-pill ${t.risk<40?'safe':t.risk<90?'elevated':'danger'}`}>{t.risk}</strong><time>{t.time}</time></button>)}</div></Card> }

export function ProgressCard({data,overall}) { return <Card title="Project Progress" className="progress-card" action={<button className="select-button">This Sprint <ChevronDown size={13}/></button>}><div className="progress-body"><div className="progress-ring"><Gauge value={overall} size={154} stroke={9} color="#7562ff"><div><strong>{overall}%</strong><span>Overall Progress</span></div></Gauge></div><div className="progress-list">{data.map(item=><div className="progress-item" key={item.label}><span className="progress-icon" style={{color:item.color,background:`${item.color}1c`}}>{item.icon}</span><div className="progress-content"><div className="progress-label"><b>{item.label}</b><span>{item.value}%</span></div><div className="progress-track"><i style={{'--progress':`${item.value}%`,'--progress-color':item.color}}/></div></div></div>)}</div></div></Card> }

export function ThreatMap({locations,data}) { return <Card title="Threat Map" className="map-card" action={<span className="live-badge"><i/> Live</span>}><div className="map-visual"><svg viewBox="0 0 560 220" role="img" aria-label="World map with active threat locations"><defs><pattern id="dots" width="4" height="4" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".8" fill="#1d5d82" opacity=".6"/></pattern><filter id="mapGlow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
    <path className="continent" d="M26 55 44 39 72 35 91 23 115 30 129 48 151 52 167 70 154 83 136 82 125 96 109 103 100 127 82 140 68 127 56 109 40 99 31 79ZM139 114 158 116 174 132 180 159 168 185 157 208 143 192 137 169 126 151ZM233 46 249 36 266 44 277 58 271 72 255 73 247 86 230 81 221 66ZM276 88 300 77 328 83 346 96 357 113 346 128 331 134 322 162 307 173 292 154 284 129 270 114ZM350 51 370 41 401 39 432 48 455 61 479 58 503 69 526 84 514 101 491 106 470 98 451 109 426 102 410 119 392 113 381 96 365 91 354 75Z" fill="url(#dots)" stroke="#155377" strokeWidth="1"/>
    <path d="M111 78 Q220 8 322 84 M144 103 Q221 139 292 122 M292 122 Q382 23 462 90 M274 126 Q284 169 289 193 M375 84 Q425 118 467 151" className="map-arc"/>
    {locations.map((p,i)=>{const item=data[p.type==='critical'?0:p.type==='high'?1:p.type==='medium'?2:3];return <g key={i} className={`map-node node-${p.type}`} transform={`translate(${p.x*5.6},${p.y*2.2})`}><circle r="8" className="node-halo"/><circle r="3.3" className="node-dot"/><title>{p.type} threat · {item?.value ?? 0} tracked</title></g>})}</svg></div><div className="map-legend">{data.map(item=><div key={item.label}><i style={{background:item.color}}/><span>{item.label}</span><b>{item.value}</b></div>)}</div></Card> }

export function ThreatTypes({data}) { const total=data.reduce((sum,item)=>sum+item.value,0), gradient=useMemo(()=>{let start=0;return `conic-gradient(${data.map(item=>{const end=start+item.value/total*100;const segment=`${item.color} ${start}% ${end}%`;start=end;return segment}).join(', ')})`},[data,total]); return <Card title="Threat Types" className="types-card" action={<button className="select-button">Last 7 Days <ChevronDown size={13}/></button>}><div className="types-body"><div className="donut" style={{background:gradient}}><div><b>{total}</b><span>Total</span></div></div><div className="types-legend">{data.map(item=><div key={item.label}><i style={{background:item.color}}/><span>{item.label}</span><b>{item.value}</b></div>)}</div></div></Card> }

export function Timeline({data,campaign}) { return <Card title="Campaign Timeline" className="timeline-card"><div className="timeline-content"><div className="campaign-summary"><span className="campaign-emblem"><ShieldAlert size={17}/></span><div><b>{campaign.id}</b><small>{campaign.relatedThreats} related threats</small></div><span className="campaign-risk">Risk: {campaign.risk}</span></div><div className="timeline-stages">{data.map((step,i)=><div className={`timeline-stage ${step.state}`} key={step.label}><span className="timeline-dot"/><b>{step.label}</b>{step.time&&<small>{step.time}</small>}{i<data.length-1&&<i className="timeline-connector"/>}</div>)}</div><button className="campaign-link">View Campaign <span>→</span></button></div></Card> }
