import { useMemo, useState } from 'react'
export default function ThreatActivity({data}){
 const [period,setPeriod]=useState('7D'),[hover,setHover]=useState(null)
 const visible=useMemo(()=>period==='24H'?data.slice(-4).map((point,index)=>({...point,day:['00h','08h','16h','24h'][index]})):period==='30D'?data.map((point,index)=>({...point,day:['Sep 9','Sep 14','Sep 19','Sep 24','Sep 29','Oct 4','Oct 8'][index],value:Math.round(point.value*1.7)})):data,[data,period])
 const valueScale=period==='30D'?2:3.6
 const points=visible.map((point,index)=>({x:36+index*(708/Math.max(visible.length-1,1)),y:152-point.value*valueScale,...point}))
 const line=points.map((point,index)=>`${index?'L':'M'}${point.x} ${point.y}`).join(' '),area=`${line} L${points.at(-1).x} 160 L${points[0].x} 160 Z`
 return <section className="card threat-activity"><header className="card-header"><div><h2>Threat Activity</h2><small>Threat detections across monitored assets</small></div><div className="period-switch">{['24H','7D','30D'].map(value=><button className={period===value?'active':''} key={value} onClick={()=>{setPeriod(value);setHover(null)}} aria-pressed={period===value}>{value}</button>)}</div></header><svg viewBox="0 0 780 190" role="img" aria-label={`Threat activity for ${period}`}><defs><linearGradient id="activity-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#16baff" stopOpacity=".24"/><stop offset="1" stopColor="#16baff" stopOpacity="0"/></linearGradient></defs>{[20,55,90,125,160].map(y=><line key={y} x1="36" x2="744" y1={y} y2={y} className="activity-gridline"/>)}<path d={area} fill="url(#activity-fill)"/><path d={line} className="activity-path"/>{points.map((point,index)=><g key={point.day} onMouseEnter={()=>setHover(index)} onMouseLeave={()=>setHover(null)} tabIndex="0" role="button" aria-label={`${point.day}: ${point.value} detections`} onFocus={()=>setHover(index)}><circle cx={point.x} cy={point.y} r={hover===index?5:3.5} className={point.value>=30?'activity-peak':'activity-dot'}/>{hover===index&&<g><rect x={point.x-35} y={point.y-42} width="70" height="30" rx="5" className="activity-tip"/><text x={point.x} y={point.y-23} textAnchor="middle" className="activity-tip-text">{point.day} · {point.value}</text></g>}<text x={point.x} y="181" textAnchor="middle" className="activity-day">{point.day}</text></g>)}</svg></section>
}
