import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Check, ChevronRight, RotateCw, Shield, ShieldAlert, X } from 'lucide-react'
import Sidebar from './components/layout/Sidebar.jsx'
import Topbar from './components/layout/Topbar.jsx'
import PageContainer from './components/layout/PageContainer.jsx'
import BackendPipeline from './components/dashboard/BackendPipeline.jsx'
import SecurityPosture from './components/dashboard/SecurityPosture.jsx'
import MetricGrid from './components/dashboard/MetricGrid.jsx'
import ThreatActivity from './components/dashboard/ThreatActivity.jsx'
import DetectionFeed from './components/dashboard/DetectionFeed.jsx'
import ThreatDrawer from './components/threats/ThreatDrawer.jsx'
import Modal from './components/ui/Modal.jsx'
import { Applications, AIAnalysis, Campaigns, Domains, EvidenceGraph, FakeAccounts, SimplePage, ThreatInbox, Vulnerabilities } from './components/pages/IntelligencePages.jsx'
import { useDashboard } from './hooks/useDashboard.js'
import { accountService } from './services/accountService.js'
import { aiService } from './services/aiService.js'
import { applicationService } from './services/applicationService.js'
import { campaignService } from './services/campaignService.js'
import { dashboardService } from './services/dashboardService.js'
import { domainService } from './services/domainService.js'
import { evidenceService } from './services/evidenceService.js'
import { scanService } from './services/scanService.js'
import { threatService } from './services/threatService.js'
import { vulnerabilityService } from './services/vulnerabilityService.js'
import { USE_MOCK_DATA } from './services/serviceFactory.js'

const pages=['Dashboard','Threat Inbox','Fake Accounts','Vulnerabilities','Domains','Applications','Campaigns','Evidence Graph','AI Analysis','Brand Assets','Reports','Settings']
const scanSteps=['Initializing AEGIS...','Connecting to authorized asset inventory...','Analyzing identities...','Analyzing domains...','Analyzing applications...','Running AI classification...','Calculating risk...','Correlating evidence...','Scan Complete']
const route=()=>{const value=decodeURIComponent(location.hash.slice(1));return pages.includes(value)?value:'Dashboard'}

function ScanModal({open,onClose,onComplete,onReview,job}) {
 const [step,setStep]=useState(-1),[result,setResult]=useState(null),[progress,setProgress]=useState(0),[scanError,setScanError]=useState(false)
 useEffect(()=>{
  if(!open){setStep(-1);setResult(null);setProgress(0);setScanError(false);return}
  if(job?.status==='demo'){
   let n=0;const timer=setInterval(()=>{n++;setStep(n-1);setProgress(Math.round(n/scanSteps.length*100));if(n>=scanSteps.length){clearInterval(timer);setResult({assetsAnalyzed:108,threatsDetected:5,critical:3,high:1,medium:1});onComplete?.()}},450)
   return()=>clearInterval(timer)
  }
  let active=true,busy=false
  const poll=async()=>{if(busy||!active)return;busy=true;try{const status=await scanService.get(job.id);if(!active)return;setProgress(status.progress||0);const state=String(status.status).toLowerCase();if(['complete','completed','failed','error'].includes(state)){if(['failed','error'].includes(state))setScanError(true);else{setResult(status);onComplete?.(status)}clearInterval(timer)}}catch{if(active){setScanError(true);clearInterval(timer)}}finally{busy=false}}
  const timer=setInterval(poll,1200);poll();return()=>{active=false;clearInterval(timer)}
 },[open,job,onComplete])
 const isDemo=job?.status==='demo'
 return <Modal open={open} title="AEGIS Authorized Asset Scan" onClose={onClose}>
  {isDemo&&<div className="scan-demo-banner"><Shield size={16}/> SIMULATED DEMO PROCESS · NO EXTERNAL SCANNING</div>}
  {scanError?<div className="scan-failure"><AlertTriangle/><h3>Scan status unavailable</h3><p>The API could not return the scan status. Check the connection and try again.</p><button onClick={onClose}>Close</button></div>:!result?<><div className="scan-progress"><span style={{width:`${progress}%`}}/></div><b className="scan-step-label">{isDemo?scanSteps[Math.max(step,0)]:'Synchronizing with authorized scan service...'}</b>{isDemo&&<ol className="scan-step-list">{scanSteps.map((label,index)=><li key={label} className={index<step?'complete':index===step?'running':''}>{index<step?<Check size={15}/>:index===step?<RotateCw size={15} className="spin"/>:<i/>}{label}</li>)}</ol>}</>:<div className="scan-results"><span className="scan-done-icon"><Check/></span><h3>Scan Complete</h3><small className="scan-result-mode">{isDemo?'DEMO MODE · MOCK DATA':'AUTHORIZED API RESULT'}</small><div><span>Assets analyzed<b>{result.assetsAnalyzed??result.assets_analyzed??0}</b></span><span>Threats detected<b>{result.threatsDetected??result.threats_detected??0}</b></span><span>Critical<b>{result.critical??0}</b></span><span>High<b>{result.high??0}</b></span><span>Medium<b>{result.medium??0}</b></span></div><button onClick={onReview}>Review detections <ChevronRight size={15}/></button></div>}
 </Modal>
 }

function Dashboard({data,threats,onSelect,onScan,onNavigate}){return <><section className="welcome hero-welcome"><div><div className="eyebrow"><span className="eyebrow-dot"/> AEGIS SECURITY OPERATIONS <span className="demo-chip">DEMO MODE · MOCK DATA</span></div><h1>Good afternoon, Security Team</h1><p>Your brand protection overview</p></div><button className="run-scan" onClick={onScan}><RotateCw size={15}/> RUN AEGIS SCAN</button></section><MetricGrid metrics={data.metrics} onSelect={name=>onNavigate(name.includes('Vulnerabilities')?'Vulnerabilities':name.includes('Accounts')?'Fake Accounts':name.includes('Domains')?'Domains':name.includes('Campaigns')?'Campaigns':'Threat Inbox')}/><div className="dashboard-top-grid"><SecurityPosture data={data.posture}/><BackendPipeline stages={data.pipeline}/></div><div className="dashboard-bottom-grid"><ThreatActivity data={data.activity}/><DetectionFeed items={threats.slice(0,5)} onSelect={onSelect} onViewAll={()=>onNavigate('Threat Inbox')}/></div><div className="dashboard-footnote"><Shield size={13}/> Demo records are illustrative. AEGIS does not scan systems until authorized API integrations are connected.</div></>}

function StatePanel({kind,message,onRetry}){return <div className={`state-panel ${kind}`}><span>{kind==='error'||kind==='offline'?<AlertTriangle/>:<RotateCw className={kind==='loading'?'spin':''}/>}</span><h2>{message}</h2>{onRetry&&<button onClick={onRetry}>Retry</button>}<small>{USE_MOCK_DATA?'DEMO MODE · MOCK DATA':'API MODE'}</small></div>}

export default function App(){const {data:baseData,error:dashboardError,loading:dashboardLoading,refresh:refreshDashboard}=useDashboard();const [page,setPage]=useState(route),[drawer,setDrawer]=useState(null),[mobileNav,setMobileNav]=useState(false),[scanOpen,setScanOpen]=useState(false),[scanNotice,setScanNotice]=useState(null),[scanJob,setScanJob]=useState(null),[records,setRecords]=useState(null),[error,setError]=useState(null),[toast,setToast]=useState('');const navigate=useCallback(next=>{setPage(next);location.hash=encodeURIComponent(next)},[]);useEffect(()=>{const change=()=>setPage(route());window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change)},[])
 const load=useCallback(async()=>{setError(null);try{const [dashboard,threats,accounts,vulnerabilities,domains,applications,campaigns,evidence,ai]=await Promise.all([dashboardService.get(),threatService.list(),accountService.list(),vulnerabilityService.list(),domainService.list(),applicationService.list(),campaignService.list(),evidenceService.get(),aiService.list()]);setRecords({dashboard,threats,accounts,vulnerabilities,domains,applications,campaigns,evidence,ai})}catch(e){setError(e);setRecords(null)}},[]);useEffect(()=>{load()},[load]);const notices=useMemo(()=>records?{threats:records.threats,accounts:records.accounts,domains:records.domains,applications:records.applications,vulnerabilities:records.vulnerabilities,campaigns:records.campaigns}:null,[records]);
 const startScan=async()=>{try{const job=await scanService.start({scope:'authorized-inventory'});setScanJob(job)}catch{setToast('Scan request failed');return}setScanNotice(null);setScanOpen(true)};const scanComplete=useCallback(result=>{const demo=USE_MOCK_DATA;setScanNotice({demo,critical:result?.critical??0});setToast(`${demo?'Demo':'Authorized API'} scan complete · ${result?.threatsDetected??result?.threats_detected??0} threats detected`);setTimeout(()=>setToast(''),5000)},[]);const resolveThreat=(item,status='Investigating')=>{setDrawer({...item,status});const key=item.id?.startsWith('ACC-')?'accounts':item.id?.startsWith('VULN-')?'vulnerabilities':item.id?.startsWith('DOM-')?'domains':item.id?.startsWith('APP-')?'applications':item.id?.startsWith('CAMP-')?'campaigns':'threats';setRecords(previous=>previous&&({...previous,[key]:previous[key].map(record=>record.id===item.id?{...record,status}:record)}));setToast(`${item.name||item.username||item.id} marked ${status.toLowerCase()}`);setTimeout(()=>setToast(''),3000)};const createCampaign=async(item)=>{try{const campaign=await campaignService.create({name:`Investigation: ${item.name||item.username||item.domain||item.id}`,risk:item.risk||item.score||50,status:'Active',threats:1,related:[item.name||item.username||item.domain||item.id],timeline:['Detected','Investigating','AI Analysis','Action Required','Takedown']});setRecords(previous=>({...previous,campaigns:[campaign,...previous.campaigns]}));setDrawer(null);navigate('Campaigns');setToast('Demo campaign created');setTimeout(()=>setToast(''),3000)}catch{setToast('Could not create campaign')}}
 if(dashboardLoading)return <StatePanel kind="loading" message="Loading AEGIS workspace..."/>;if(dashboardError)return <StatePanel kind="error" message="Could not load dashboard." onRetry={()=>{refreshDashboard();load()}}/>;if(!records)return <StatePanel kind={error?.code==='OFFLINE'?'offline':'error'} message={error?.code==='OFFLINE'?'API offline. Check your connection.':'Failed to load intelligence records.'} onRetry={load}/>;
 const data={...baseData,...records.dashboard};const detailProps={onSelect:setDrawer};let content;switch(page){case'Dashboard':content=<Dashboard data={data} threats={records.threats} onSelect={setDrawer} onScan={startScan} onNavigate={navigate}/>;break;case'Threat Inbox':content=<ThreatInbox rows={records.threats} {...detailProps}/>;break;case'Fake Accounts':content=<FakeAccounts rows={records.accounts} {...detailProps}/>;break;case'Vulnerabilities':content=<Vulnerabilities rows={records.vulnerabilities} {...detailProps}/>;break;case'Domains':content=<Domains rows={records.domains} {...detailProps}/>;break;case'Applications':content=<Applications rows={records.applications} {...detailProps}/>;break;case'Campaigns':content=<Campaigns rows={records.campaigns} {...detailProps}/>;break;case'Evidence Graph':content=<EvidenceGraph data={records.evidence} onSelect={setDrawer}/>;break;case'AI Analysis':content=<AIAnalysis rows={records.ai}/>;break;default:content=<SimplePage page={page} data={records.threats} onNavigate={navigate}/>}
 return <div className="app-shell"><Sidebar active={page==='Dashboard'?'Overview':page} onNavigate={navigate} open={mobileNav} onClose={()=>setMobileNav(false)} data={{brand:{name:'PaySecure',assets:108,campaigns:records.campaigns.length}}}/><main className="main-area"><Topbar onMenu={()=>setMobileNav(true)} overview={baseData.overview} records={notices} onSelectThreat={setDrawer} onNavigate={navigate} scanComplete={scanNotice}/><PageContainer>{content}<footer className="content-footer"><span>AEGIS · AI BRAND THREAT INTELLIGENCE <i>·</i> {USE_MOCK_DATA?'DEMO MODE · MOCK DATA':'API MODE'}</span><span><i/> AUTHORIZED SCOPE ONLY</span></footer></PageContainer></main><ThreatDrawer record={drawer} onClose={()=>setDrawer(null)} onResolve={resolveThreat} onCampaign={createCampaign} onEvidence={()=>{setDrawer(null);navigate('Evidence Graph')}}/><ScanModal open={scanOpen} onClose={()=>setScanOpen(false)} onComplete={scanComplete} onReview={()=>{setScanOpen(false);navigate('Threat Inbox')}} job={scanJob}/>{toast&&<div className="toast-notice" role="status"><Check size={15}/>{toast}<button aria-label="Dismiss" onClick={()=>setToast('')}><X size={14}/></button></div>}</div>
}
